{% set name = "napari-workshop-browser" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-workshop-browser-{{ version }}.tar.gz
  sha256: c3227fa992d309d2a28ae7339ade3b14c60149b53c9c452f36446262bb364a24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - appdirs
    - jupytext
    - notebook <7.0.0
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - requests
    - superqt

test:
  imports:
    - napari_workshop_browser
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/kephale/napari-workshop-browser
  summary: A plugin to browse and follow napari workshops
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kephale
